FROM ghcr.io/developmentseed/titiler:latest

# Enable unsigned reads of public Copernicus buckets
ENV AWS_NO_SIGN_REQUEST=YES
ENV GDAL_DISABLE_READDIR_ON_OPEN=EMPTY_DIR
ENV VSI_CACHE=TRUE
ENV VSI_CACHE_SIZE=5000000

EXPOSE 8081

CMD ["uvicorn", "titiler.application.main:app", "--host", "0.0.0.0", "--port", "8081"]
